CREATE TABLE TIPO_SOPORTE (
	ID_TIPO_SOPORTE SERIAL PRIMARY KEY,
	DESCRIPCION VARCHAR(30) NOT NULL,
	SIGLADO VARCHAR(5) NOT NULL
);

INSERT INTO TIPO_SOPORTE (DESCRIPCION, SIGLADO) VALUES ('SOPORTE TECNICO REMOTO', 'STR');
INSERT INTO TIPO_SOPORTE (DESCRIPCION, SIGLADO) VALUES ('SOPORTE TECNICO A DOMICILIO', 'STD');

--SELECT * FROM TIPO_SOPORTE

CREATE TABLE ESTADO_SOLICITUD (
	ID_ESTADO_SOLICITUD SERIAL PRIMARY KEY,
	ESTADO VARCHAR(30) NOT NULL
);

INSERT INTO ESTADO_SOLICITUD (ESTADO) VALUES ('SOLICITADO');
INSERT INTO ESTADO_SOLICITUD (ESTADO) VALUES ('ASIGNADO');
INSERT INTO ESTADO_SOLICITUD (ESTADO) VALUES ('RESULTO');
INSERT INTO ESTADO_SOLICITUD (ESTADO) VALUES ('CANCELADO');

--SELECT * FROM ESTADO_SOLICITUD

CREATE TABLE TECNICO (
	ID_TECNICO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL
);

INSERT INTO TECNICO (NOMBRE) VALUES ('GUILLERMO');
INSERT INTO TECNICO (NOMBRE) VALUES ('RENZO');
INSERT INTO TECNICO (NOMBRE) VALUES ('FRANCO');

--SELECT * FROM TECNICO

--DROP TABLE SOLICITUD
CREATE TABLE SOLICITUD (
	ID_SOLICITUD SERIAL PRIMARY KEY,
	ID_TIPO_SOPORTE INT NOT NULL,
	FECHA_SOLICITUD DATE NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	TELEFONO VARCHAR(20) NULL,
	DESCRIPCION_PROBLEMA VARCHAR(255) NOT NULL,
	CALLE VARCHAR(30) NOT NULL,
	NUMERO INT NOT NULL,
	PISO_Y_DEPTO VARCHAR(10) NULL,
	LOCALIDAD VARCHAR(30) NULL,
	PROVINCIA VARCHAR(30) NULL,
	ID_TECNICO INT NULL,
	ID_ESTADO_SOLICITUD INT NULL,
	FECHA_CIERRE DATE NULL,
	FOREIGN KEY (ID_TIPO_SOPORTE) REFERENCES TIPO_SOPORTE(ID_TIPO_SOPORTE),
	FOREIGN KEY (ID_TECNICO) REFERENCES TECNICO(ID_TECNICO),
	FOREIGN KEY (ID_ESTADO_SOLICITUD) REFERENCES ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD)
);

CREATE INDEX idx_tipo_soporte ON SOLICITUD(ID_TIPO_SOPORTE);
CREATE INDEX idx_tecnico ON SOLICITUD(ID_TECNICO);
CREATE INDEX idx_estado_solicitud ON SOLICITUD(ID_ESTADO_SOLICITUD);

--SELECT * FROM SOLICITUD