CREATE TABLE SOLICITUDES (
	ID_SOLICITUD SERIAL PRIMARY KEY,
	FECHA_SOLICITUD DATE NOT NULL DEFAULT CURRENT_DATE,
	NOMBRE VARCHAR(30) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	TELEFONO VARCHAR(20) NULL,
	DESCRIPCION_PROBLEMA VARCHAR(255) NOT NULL,
    TECNICO_ASIGNADO BOOLEAN NOT NULL DEFAULT FALSE,
	ESTADO_SOLICITUD BOOLEAN NOT NULL DEFAULT FALSE,
	FECHA_CIERRE DATE NULL
);

--SELECT * FROM SOLICITUDES